### ISSUE TITLE
Metal3: helm dependency update . failes

### ISSUE THREAD

**Issue by fedcicchiello** [suse-edge/charts#14]
When trying to update Metal3's charts dependencies I got:
`Error: dependency "baremetal-operator" has an invalid version/constraint format: improper constraint:`

The reason is that in [charts/metal3-deploy/0.1.0/Chart.yaml](https://github.com/suse-edge/charts/blob/079f28a17b5fe81481310821f3c6e5f1ec9d8f70/charts/metal3-deploy/0.1.0/Chart.yaml) for each dependency the `version` key is missing but it is actually required.

I figured out that this was the reason I encountered the issue #10 (and opened #11) but I think we can close them and leave this one since by fixing the dependencies' version field properly also the aliases `metal3-<subchart name>` work.

**Comment by dbw7** [comment]
For the moment, I think all of the issues you've encountered are fixed within my fork linked here: [https://github.com/dbw7/charts](https://github.com/dbw7/charts)  

Test out the charts in the [/charts directory](https://github.com/dbw7/charts/tree/main/charts/metal3-deploy/0.1.0) but do note that the charts in /packages and /assets are outdated at the moment because of an issue with the chart building scripts that we will discuss with the team.

Give it a try and let me know if you run into any issues 😄

**Comment by dbw7** [comment]
Hello, this issue has been fixed in #15
